services:
  server:
    container_name: shishki_server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    command:
      sh -c "cd /server && node ./dist/index.js"
